# Sử dụng base image Nginx (bản nhẹ)
FROM nginx:1.25-alpine

# Xóa file config Nginx mặc định (nếu cần)
# RUN rm /etc/nginx/conf.d/default.conf

# Sao chép TOÀN BỘ file tĩnh (index.html, style.css...) vào thư mục web root của Nginx
COPY . /usr/share/nginx/html

# Mở cổng 80
EXPOSE 80

# Lệnh để Nginx chạy ở foreground
CMD ["nginx", "-g", "daemon off;"]